/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as SigninImport } from './routes/signin'
import { Route as RostersImport } from './routes/rosters'
import { Route as RedirectImport } from './routes/redirect'
import { Route as LiveFeedImport } from './routes/live-feed'
import { Route as LazyComponentImport } from './routes/lazy-component'
import { Route as DiscoverUnclaimedImport } from './routes/discover-unclaimed'
import { Route as DealsImport } from './routes/deals'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'
import { Route as AdminIndexImport } from './routes/admin.index'
import { Route as UnclaimedProfileIdImport } from './routes/unclaimed-profile.$id'
import { Route as AdminMembersImport } from './routes/admin.members'
import { Route as AdminMembersIndexImport } from './routes/admin.members.index'
import { Route as AdminMembersMemberIdImport } from './routes/admin.members.$memberId'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const SigninRoute = SigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const RostersRoute = RostersImport.update({
  id: '/rosters',
  path: '/rosters',
  getParentRoute: () => rootRoute,
} as any)

const RedirectRoute = RedirectImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRoute,
} as any)

const LiveFeedRoute = LiveFeedImport.update({
  id: '/live-feed',
  path: '/live-feed',
  getParentRoute: () => rootRoute,
} as any)

const LazyComponentRoute = LazyComponentImport.update({
  id: '/lazy-component',
  path: '/lazy-component',
  getParentRoute: () => rootRoute,
} as any)

const DiscoverUnclaimedRoute = DiscoverUnclaimedImport.update({
  id: '/discover-unclaimed',
  path: '/discover-unclaimed',
  getParentRoute: () => rootRoute,
} as any)

const DealsRoute = DealsImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)

const UnclaimedProfileIdRoute = UnclaimedProfileIdImport.update({
  id: '/unclaimed-profile/$id',
  path: '/unclaimed-profile/$id',
  getParentRoute: () => rootRoute,
} as any)

const AdminMembersRoute = AdminMembersImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)

const AdminMembersIndexRoute = AdminMembersIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminMembersRoute,
} as any)

const AdminMembersMemberIdRoute = AdminMembersMemberIdImport.update({
  id: '/$memberId',
  path: '/$memberId',
  getParentRoute: () => AdminMembersRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsImport
      parentRoute: typeof rootRoute
    }
    '/discover-unclaimed': {
      id: '/discover-unclaimed'
      path: '/discover-unclaimed'
      fullPath: '/discover-unclaimed'
      preLoaderRoute: typeof DiscoverUnclaimedImport
      parentRoute: typeof rootRoute
    }
    '/lazy-component': {
      id: '/lazy-component'
      path: '/lazy-component'
      fullPath: '/lazy-component'
      preLoaderRoute: typeof LazyComponentImport
      parentRoute: typeof rootRoute
    }
    '/live-feed': {
      id: '/live-feed'
      path: '/live-feed'
      fullPath: '/live-feed'
      preLoaderRoute: typeof LiveFeedImport
      parentRoute: typeof rootRoute
    }
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectImport
      parentRoute: typeof rootRoute
    }
    '/rosters': {
      id: '/rosters'
      path: '/rosters'
      fullPath: '/rosters'
      preLoaderRoute: typeof RostersImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersImport
      parentRoute: typeof AdminImport
    }
    '/unclaimed-profile/$id': {
      id: '/unclaimed-profile/$id'
      path: '/unclaimed-profile/$id'
      fullPath: '/unclaimed-profile/$id'
      preLoaderRoute: typeof UnclaimedProfileIdImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminImport
    }
    '/admin/members/$memberId': {
      id: '/admin/members/$memberId'
      path: '/$memberId'
      fullPath: '/admin/members/$memberId'
      preLoaderRoute: typeof AdminMembersMemberIdImport
      parentRoute: typeof AdminMembersImport
    }
    '/admin/members/': {
      id: '/admin/members/'
      path: '/'
      fullPath: '/admin/members/'
      preLoaderRoute: typeof AdminMembersIndexImport
      parentRoute: typeof AdminMembersImport
    }
  }
}

// Create and export the route tree

interface AdminMembersRouteChildren {
  AdminMembersMemberIdRoute: typeof AdminMembersMemberIdRoute
  AdminMembersIndexRoute: typeof AdminMembersIndexRoute
}

const AdminMembersRouteChildren: AdminMembersRouteChildren = {
  AdminMembersMemberIdRoute: AdminMembersMemberIdRoute,
  AdminMembersIndexRoute: AdminMembersIndexRoute,
}

const AdminMembersRouteWithChildren = AdminMembersRoute._addFileChildren(
  AdminMembersRouteChildren,
)

interface AdminRouteChildren {
  AdminMembersRoute: typeof AdminMembersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMembersRoute: AdminMembersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/deals': typeof DealsRoute
  '/discover-unclaimed': typeof DiscoverUnclaimedRoute
  '/lazy-component': typeof LazyComponentRoute
  '/live-feed': typeof LiveFeedRoute
  '/redirect': typeof RedirectRoute
  '/rosters': typeof RostersRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/admin/members': typeof AdminMembersRouteWithChildren
  '/unclaimed-profile/$id': typeof UnclaimedProfileIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/members/$memberId': typeof AdminMembersMemberIdRoute
  '/admin/members/': typeof AdminMembersIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/deals': typeof DealsRoute
  '/discover-unclaimed': typeof DiscoverUnclaimedRoute
  '/lazy-component': typeof LazyComponentRoute
  '/live-feed': typeof LiveFeedRoute
  '/redirect': typeof RedirectRoute
  '/rosters': typeof RostersRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/unclaimed-profile/$id': typeof UnclaimedProfileIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/members/$memberId': typeof AdminMembersMemberIdRoute
  '/admin/members': typeof AdminMembersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/deals': typeof DealsRoute
  '/discover-unclaimed': typeof DiscoverUnclaimedRoute
  '/lazy-component': typeof LazyComponentRoute
  '/live-feed': typeof LiveFeedRoute
  '/redirect': typeof RedirectRoute
  '/rosters': typeof RostersRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/admin/members': typeof AdminMembersRouteWithChildren
  '/unclaimed-profile/$id': typeof UnclaimedProfileIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/members/$memberId': typeof AdminMembersMemberIdRoute
  '/admin/members/': typeof AdminMembersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/deals'
    | '/discover-unclaimed'
    | '/lazy-component'
    | '/live-feed'
    | '/redirect'
    | '/rosters'
    | '/signin'
    | '/signup'
    | '/admin/members'
    | '/unclaimed-profile/$id'
    | '/admin/'
    | '/admin/members/$memberId'
    | '/admin/members/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/deals'
    | '/discover-unclaimed'
    | '/lazy-component'
    | '/live-feed'
    | '/redirect'
    | '/rosters'
    | '/signin'
    | '/signup'
    | '/unclaimed-profile/$id'
    | '/admin'
    | '/admin/members/$memberId'
    | '/admin/members'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/deals'
    | '/discover-unclaimed'
    | '/lazy-component'
    | '/live-feed'
    | '/redirect'
    | '/rosters'
    | '/signin'
    | '/signup'
    | '/admin/members'
    | '/unclaimed-profile/$id'
    | '/admin/'
    | '/admin/members/$memberId'
    | '/admin/members/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DealsRoute: typeof DealsRoute
  DiscoverUnclaimedRoute: typeof DiscoverUnclaimedRoute
  LazyComponentRoute: typeof LazyComponentRoute
  LiveFeedRoute: typeof LiveFeedRoute
  RedirectRoute: typeof RedirectRoute
  RostersRoute: typeof RostersRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  UnclaimedProfileIdRoute: typeof UnclaimedProfileIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DealsRoute: DealsRoute,
  DiscoverUnclaimedRoute: DiscoverUnclaimedRoute,
  LazyComponentRoute: LazyComponentRoute,
  LiveFeedRoute: LiveFeedRoute,
  RedirectRoute: RedirectRoute,
  RostersRoute: RostersRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  UnclaimedProfileIdRoute: UnclaimedProfileIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/dashboard",
        "/deals",
        "/discover-unclaimed",
        "/lazy-component",
        "/live-feed",
        "/redirect",
        "/rosters",
        "/signin",
        "/signup",
        "/unclaimed-profile/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx",
      "children": [
        "/admin/members",
        "/admin/"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/deals": {
      "filePath": "deals.tsx"
    },
    "/discover-unclaimed": {
      "filePath": "discover-unclaimed.tsx"
    },
    "/lazy-component": {
      "filePath": "lazy-component.tsx"
    },
    "/live-feed": {
      "filePath": "live-feed.tsx"
    },
    "/redirect": {
      "filePath": "redirect.tsx"
    },
    "/rosters": {
      "filePath": "rosters.tsx"
    },
    "/signin": {
      "filePath": "signin.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/admin/members": {
      "filePath": "admin.members.tsx",
      "parent": "/admin",
      "children": [
        "/admin/members/$memberId",
        "/admin/members/"
      ]
    },
    "/unclaimed-profile/$id": {
      "filePath": "unclaimed-profile.$id.tsx"
    },
    "/admin/": {
      "filePath": "admin.index.tsx",
      "parent": "/admin"
    },
    "/admin/members/$memberId": {
      "filePath": "admin.members.$memberId.tsx",
      "parent": "/admin/members"
    },
    "/admin/members/": {
      "filePath": "admin.members.index.tsx",
      "parent": "/admin/members"
    }
  }
}
ROUTE_MANIFEST_END */
